# appveyor.yml

# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml

environment:
  YKPERS_VERSION: "1.19.0"
  LIBUSB_VERSION: "1.0.21"
  YKPERS_BASEURL: https://developers.yubico.com/yubikey-personalization/Releases

  matrix:
    - platform: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python36
      WIN_ARCH: win32
      LIBUSB_DLL_FOLDER: MS32

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python36-x64
      WIN_ARCH: win64
      LIBUSB_DLL_FOLDER: MS64

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - echo %PATH%

install:
  - choco install swig -y
  - choco upgrade swig

  - ps: wget "$env:YKPERS_BASEURL/ykpers-$env:YKPERS_VERSION-$env:WIN_ARCH.zip" -OutFile "ykpers-$env:YKPERS_VERSION-$env:WIN_ARCH.zip"
  - 7z x ykpers-%YKPERS_VERSION%-%WIN_ARCH%.zip -o".\ykpers"
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\ykpers\bin
  - ps: Copy-Item ".\ykpers\bin\*.dll" "." -Force -verbose

  - ps: Invoke-WebRequest "http://prdownloads.sourceforge.net/libusb/libusb-$env:LIBUSB_VERSION.7z" -OutFile "libusb-$env:LIBUSB_VERSION.7z" -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
  - 7z x libusb-%LIBUSB_VERSION%.7z -o".\libusb"
  - ps: Copy-Item ".\libusb\$env:LIBUSB_DLL_FOLDER\dll\*.dll" "." -Force -verbose

build_script:
  - pip install .
  - pip install pyinstaller
  - pyinstaller --console --onefile --clean ykman.spec

after_build:
  - set ARTIFACT_NAME=%APPVEYOR_REPO_BRANCH%-%WIN_ARCH%
  - if defined APPVEYOR_REPO_TAG_NAME set ARTIFACT_NAME=%APPVEYOR_REPO_TAG_NAME%-%WIN_ARCH%
  - 7z a yubikey-manager-%ARTIFACT_NAME%.zip .\dist\*

artifacts:
  - path: yubikey-manager-$(ARTIFACT_NAME).zip

deploy:
  - provider: S3
    access_key_id: $(AWS_KEY_ID)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: $(AWS_BUCKET)
    folder: "yubikey-manager"
    region: eu-west-1
    set_public: true
